from log_test1 import  logger



logger.error('wow!!!')